### ISSUE TITLE
Add `init` command

### ISSUE THREAD

**Issue by Rakhyvel** [Rakhyvel/Orng#53]
The command should:
1. Check to see if there is already a `build.orng` file or a `main.orng` file already in the current working directory.
2. If so, it should print an error, and exit with a status of 1.
3. If not, it should create the files with the following contents:

`main.orng`:
```rs
import std::debug

fn main() -> () {
    debug::println("Hello, World!")
}
```

`build.orng`:
```rs
fn build() -> Package {
    Package::executable(.root="main.orng")
}
```

**Comment by dellzer** [comment]
Hello! I've recently discovered this repo, and it does look interesting, and I am interesting into looking into this issue. The issue is that I have no experience with Zig, but rather C. Even so, it seems I could learn enough Zig to approach this. However, what file should this function be added to?

**Comment by Rakhyvel** [comment]
Hello @dellzer, great to see your interest! If you're comfortable learning zig, this is an excellent opportunity. 

The file in question is `src/main.zig`. There should be a constant called `command_table`, which holds all the commands. Each entry in the table has a name, help info, and a function pointer to the function that's ran when the command is selected.

I'd like for you to add an `init` command, which creates a `build.orng` and `main.orng` file in the current working directory. It should also print an error if a `build.orng` **or** `main.orng` file are already in the current working directory. I've edited the issue to be a bit more descriptive on what I want.

Unfortunately for now, the created package won't build until more of the build system is implemented. But just getting the files created will be enough for this issue.

Thanks!
