### ISSUE TITLE
Remove newlines in `std.debug.panic` messages

### ISSUE THREAD

**Issue by Rakhyvel** [Rakhyvel/Orng#88]
There are a handful of `std.debug.panic` calls, which contain newlines at the end of their messages. 

An example:
![image](https://github.com/user-attachments/assets/8175a21c-c9a4-4675-a1c3-cb195651f16c)

These newlines at the end of `std.debug.panic` call messages are actually redundant (`std.debug.panic` already prints a newline at the end of a message), and should be removed.

**Comment by paulmupenda** [comment]
Hello, I am a beginner, how can I help to solve this issue.?
